<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit9131b7c9c9204b7f9509d870e122e6e8
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit9131b7c9c9204b7f9509d870e122e6e8::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit9131b7c9c9204b7f9509d870e122e6e8::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit9131b7c9c9204b7f9509d870e122e6e8::$classMap;

        }, null, ClassLoader::class);
    }
}
